### ISSUE TITLE
48mp camera issue

### ISSUE THREAD

**Issue by anastabiti** [xiaomi-mt6853-devs/releases#11]
Redmi note 9t 5g (cannong) 48mp camera is not working in all versions of this custom LineageOS
   , is there any hope to find a solution to this problem , also the quality of images are very low compared to original stock frameware. thanks

**Comment by kamlandan** [comment]
I think you can use the google camera URL:https://www.celsoazevedo.com/files/android/google-camera/dev-bsg/     ,This camera can take beauitfull photos with my Redmi note 9 5g (cannon).

**Comment by LinkBoi00** [comment]
WONTFIX due to how Xiaomi implements 48MP mode. Sorry.

**Comment by anastabiti** [comment]
switch back to miui rom
