### ISSUE TITLE
Cannot open CIT - cannong

### ISSUE THREAD

**Issue by matta4102** [xiaomi-mt6853-devs/releases#13]
Cannot open CIT through either tapping on the kernel version (greyed out text instead of normal white) or dialing in *#*#6484#*#*.
I am trying to get my fingerprint sensor to work again. Also do I need to flash the _firmware_ 13.0.3.0, or is the _fastboot_ 13.0.3.0 good enough? After which i ofc installed LOS as per the guide. Thank you for fixing my laggy phone btw, your project works great.

**Comment by LinkBoi00** [comment]
*#*#3646633#*#* is the correct code if you want engineer mode. CIT is not available in custom roms at all.
