### ISSUE TITLE
The charging bug has not been completely resolved.

### ISSUE THREAD

**Issue by sunyihao425425** [xiaomi-mt6853-devs/releases#14]
Although it has a charging animation, it still restarts after charging for a while and restarts to the charging animation page. The cycle goes on and on. Is there any good solution?

**Comment by LinkBoi00** [comment]
f I forgot to push my kernel changes, sorry

**Comment by LinkBoi00** [comment]
Uh it works fine here

**Comment by LinkBoi00** [comment]
after how much time does it restart? I had my phone plugged in for an hour and nothing like this happened. Do you maybe flash another kernel?

**Comment by sunyihao425425** [comment]
It should be the reason why I used kernelsu, and the kernel should be a little old.

**Comment by LinkBoi00** [comment]
Yeah, don't report bugs without using the included kernel for that specific reason. I had fixed that specific issue with commit https://github.com/xiaomi-mt6853-devs/android_kernel_xiaomi_cannon/commit/1bca205b7aa27b187407546c51707467fe366c98

**Comment by sunyihao425425** [comment]
I'll try it over.
