### ISSUE TITLE
Can't add work profile

### ISSUE THREAD

**Issue by sverleis** [xiaomi-mt6853-devs/releases#2]
> A work profile can't be added to this device. If you have questions, contact your IT admin

Did some digging, and there isn't much on XDA, but there is this reddit post:
https://www.reddit.com/r/LineageOS/comments/87dy69/android_for_work_afw_cant_create_work_profile/

Would it be possible to add this functionality in the next update to 2?

**Comment by LinkBoi00** [comment]
Please describe the issue in more detail. I have tested this with TestDPC and it seemed to be okay.

**Comment by LinkBoi00** [comment]
Closed due to lack of activity
