### ISSUE TITLE
Any update in the pipe ? <3

### ISSUE THREAD

**Issue by paulalbertdev** [xiaomi-mt6853-devs/releases#3]
Hi, this rom is pure fire ! Before anything else, thanks a lot for your work, everything works perfectly ! 
I've got a question tho, you've seen it coming :) 
Do you plan to update it to the latest Lineage 20.0 version with security updates ? Or maye to have it integrated to the official Lineage OS releases ?

**Comment by LinkBoi00** [comment]
Irrelevant
