### ISSUE TITLE
Encrypt will causes reboot

### ISSUE THREAD

**Issue by QwQIsHidden** [xiaomi-mt6853-devs/releases#5]
The system will reboot if you encrypt or decrypt data such as Google safe code or Microsoft authenticator or export tunnel from wireguard.

**Comment by LinkBoi00** [comment]
You need to provide more details

**Comment by QwQIsHidden** [comment]
> You need to provide more details

This issue has been fixed in the latest version you released.

**Comment by LinkBoi00** [comment]
Good to know I suppose but I did nothing specific to fix this.
