### ISSUE TITLE
Gps functionality is completely unusable since release 9 

### ISSUE THREAD

**Issue by rafik24** [xiaomi-mt6853-devs/releases#6]
Hi All,

First of all thank you for the great work putting a decent OS for the note 9T.

Since I upgraded GPS functionality is unusable on gmaps and waze.

I keep getting no GPS coverage and my geolocation is completely off.

I tried all I could in vain.

Can I downgrade to release 8 ?

Many thanks,
Rafik

**Comment by LinkBoi00** [comment]
You're missing key details in your bug report. Include logs, screenshots etc. I don't have your issue by the way.

**Comment by LinkBoi00** [comment]
Make sure to also download a GPS test app (GPSTest from FDroid for example) and check if it finds any sattelites. If it does, then it's likely an app or google apps issue but surely not LOS's fault.

**Comment by LinkBoi00** [comment]
Any update on this?
