### ISSUE TITLE
Unable to use gpay and banking apps

### ISSUE THREAD

**Issue by rafik24** [xiaomi-mt6853-devs/releases#8]
Hi All,

Since I updated to latest release no banking or payment app works as it says the phone has been identified as rooted.

Is the latest releases really rooted ?

Could this please be fixed in the future ?

Is there a way to downgrade ?

Many thanks in advance.

**Comment by LinkBoi00** [comment]
No it won't be fixed. No part of upstream LineageOS will ever include SafetyNet/Play Integrity hacks. As for the hacks I used to include, no, they won't be included again. Google keeps banning old fingerprints and it's a cat and mouse game at this point.
