### ISSUE TITLE
 Help, after flashing this rom, there is no shutdown and charging animation

### ISSUE THREAD

**Issue by sunyihao425425** [xiaomi-mt6853-devs/releases#9]
Since I flashed this rom, everything else feels good to me, but when I turn it off and charge it, there is no animation and it always turns on. Is there anything that can solve this problem? Model note9 5g

**Comment by LinkBoi00** [comment]
I'll look at the issue

**Comment by sunyihao425425** [comment]
thank you

**Comment by LinkBoi00** [comment]
Fixed

**Comment by sunyihao425425** [comment]
What does it mean? Does it mean repair?

**Comment by LinkBoi00** [comment]
Fixed in codebase. The next build won't have this issue.

**Comment by sunyihao425425** [comment]
thank you
